import Head from "next/head";
import Nav from "./Nav";

export default function Layout({ children }) {
  return (
    <div className="mx-14">
      <Head>
        <title>Firebase</title>
        <meta name="description" content="Generated by create next app" />
        <script src="https://cdn.tailwindcss.com"></script>
      </Head>
      <Nav />
      <main>{children}</main>
    </div>
  );
}
