import Link from "next/link";
import { useAuthState } from "react-firebase-hooks/auth";
import { auth } from "../utils/firebase";
import Head from "next/head";

export default function () {
  const [user, loading] = useAuthState(auth);
  return (
    <>
      <Head>
        <title>Firebase</title>
        <meta name="description" content="Generated by create next app" />
        <script src="https://cdn.tailwindcss.com"></script>
      </Head>
      <nav className="flex justify-between items-center py-10">
        <Link href={"/"}>Logo</Link>
        <ul>
          {!user ? (
            <Link href={"/auth/login"}>
              <button className="py-2 px-4 text-lg bg-teal-500 text-white rounded-lg font-medium ml-8">
                Join now
              </button>
            </Link>
          ) : (
            <div>
              <Link href={"/dashboard"}>
                <img
                  src={user.photoURL}
                  alt="avator"
                  referrerPolicy="no-referrer"
                  className="w-12 rounded-full"
                />
              </Link>
            </div>
          )}
        </ul>
      </nav>
    </>
  );
}
