import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Firebase</title>
        <meta name="description" content="Generated by create next app" />
        <script src="https://cdn.tailwindcss.com"></script>
      </Head>
      <main>
        <h2 className="text-2xl mt-10">Upgrade your web development today</h2>
      </main>
    </div>
  );
}
